
version: '2'

services:
    apache:
        container_name: apache-container
        build: ./apache
        ports:
        - "80:80"
        volumes:
        - .:/root

    rails:
        container_name: rails-container
        build: ./rails
        ports:
            - "3000:3000"
        volumes:
            - .:/root
        tty: true

volumes:
    data: {}
