# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20df9f06b1eed44424674d451676bdf0c28ee8d340ad6760c7709721e92e0ffc971167faa59ba8a34465125343ec770f98b6f9b355c01c8603c6839335fe656a

test:
  secret_key_base: 4844c54ebcff51fe0ef62495d39645842911611b977cbecff0987c0886178909e9af39e837b3c956cd5ebb249faaa1a49cd5102d12527d40c6a1685de4809d70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
